name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: write
  actions: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install pre-commit
      run: pip install pre-commit
      
    - name: Run pre-commit
      run: pre-commit run --all-files
      continue-on-error: true
      
    - name: Check for changes (excluding workflows)
      id: check_changes
      run: |
        # Add all changes
        git add .
        # Remove workflow files from staging
        git reset -- .github/workflows/ || true
        # Check if there are any staged changes
        if [ -n "$(git diff --cached --name-only)" ]; then
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected (excluding workflows)"
        else
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes to commit"
        fi
        
    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git commit -m "style: auto-fix pre-commit issues

        [skip ci]"
        git push
