name: Auto-fix via Pull Request

on:
  push:
    branches: [main, master]

permissions:
  contents: write
  pull-requests: write

jobs:
  auto-fix:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install pre-commit
      run: pip install pre-commit
      
    - name: Run pre-commit
      run: pre-commit run --all-files
      continue-on-error: true
      
    - name: Create Pull Request with fixes
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        commit-message: 'style: auto-fix pre-commit issues'
        title: '🤖 Auto-fix: Pre-commit Issues'
        body: |
          This PR contains automatic fixes for pre-commit issues:
          
          - Fixed code formatting
          - Removed trailing whitespace
          - Fixed linting issues
          - Cleaned up imports
          
          Please review and merge if the changes look good!
        branch: auto-fix/pre-commit-${{ github.run_number }}
        delete-branch: true