name: Pre-commit

on:
  pull_request:
  push:
    branches: [main, master]

permissions:
  contents: write
  actions: read

jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        
    - name: Install pre-commit
      run: pip install pre-commit
      
    - name: Run pre-commit
      run: pre-commit run --all-files
      continue-on-error: true
      
    - name: Auto-commit fixes (excluding workflow files)
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: 'style: auto-fix pre-commit issues'
        skip_dirty_check: true
        file_pattern: '.github/workflows/*'